name: VillagerBiomeSwapper
version: ${project.version}
main: me.Eggses.villagerBiomeSwapper.VillagerBiomeSwapper
api-version: '1.21'
load: STARTUP
authors: [ Eggses ]
description: Plugin that lets you swap the biome of Villagers!

commands:
  villagerbiomeswapper:
    description: Base command for the Villager Biome Swapper plugin.
    usage: /<command> <subcommand>
    aliases:
      - vbs
    permission: villagerbiomeswapper.base

permissions:

  villagerbiomeswapper.*:
    description: Grants access to all features.
    default: op
    children:
      villagerbiomeswapper.reload: true

  villagerbiomeswapper.base:
    description: Ability to use base command.
    default: op

  villagerbiomeswapper.reload:
    description: Allows use of the /vbs reload command.
    default: op
    children:
      villagerbiomeswapper.base: true

  villagerbiomeswapper.give:
    description: Allows use of the /vbs give [player] and /vbs giveall commands.
    default: op
    children:
      villagerbiomeswapper.base: true

  villagerbiomeswapper.help:
    description: Allows use of the /vbs help command
    default: op
    children:
      villagerbiomeswapper.base: true


  villagerbiomeswapper.convert.*:
    description: Allows converting of all converting villagers to any biome variant.
    default: op
    children:
      villagerbiomeswapper.convert.biome.*: true
      villagerbiomeswapper.convert.entity.villager: true

  villagerbiomeswapper.convert.biome.*:
    description: Allows converting villagers to any biome variant
    default: op
    children:
      villagerbiomeswapper.convert.biome.desert: true
      villagerbiomeswapper.convert.biome.jungle: true
      villagerbiomeswapper.convert.biome.plains: true
      villagerbiomeswapper.convert.biome.savanna: true
      villagerbiomeswapper.convert.biome.snow: true
      villagerbiomeswapper.convert.biome.swamp: true
      villagerbiomeswapper.convert.biome.taiga: true


  villagerbiomeswapper.convert.biome.desert:
    description: Allows converting villagers to the desert biome variant.
    default: op
    children:
      villagerbiomeswapper.convert.entity.villager: true
  villagerbiomeswapper.convert.biome.jungle:
    description: Allows converting villagers to the jungle biome variant
    default: op
    children:
      villagerbiomeswapper.convert.entity.villager: true
  villagerbiomeswapper.convert.biome.plains:
    description: Allows converting villagers to the plains biome variant
    default: op
    children:
      villagerbiomeswapper.convert.entity.villager: true
  villagerbiomeswapper.convert.biome.savanna:
    description: Allows converting villagers to the savanna biome variant
    default: op
    children:
      villagerbiomeswapper.convert.entity.villager: true
  villagerbiomeswapper.convert.biome.snow:
    description: Allows converting villagers to the snow biome variant
    default: op
    children:
      villagerbiomeswapper.convert.entity.villager: true
  villagerbiomeswapper.convert.biome.swamp:
    description: Allows converting villagers to the swamp biome variant
    default: op
    children:
      villagerbiomeswapper.convert.entity.villager: true
  villagerbiomeswapper.convert.biome.taiga:
    description: Allows converting villagers to the taiga biome variant
    default: op
    children:
      villagerbiomeswapper.convert.entity.villager: true

  villagerbiomeswapper.convert.entity.villager:
    description: Allows converting villagers to different biome variants.
    default: op











