name: VillagerBiomeSwapper
version: ${project.version}
main: me.Eggses.villagerBiomeSwapper.VillagerBiomeSwapper
api-version: '1.21'
load: STARTUP
authors: [ Eggses ]
description: Plugin that lets you swap the biome of Villagers!

commands:


permissions:

